using System.Buffers.Binary;
using System.Security.Cryptography;
using TPW.PS2.Data;

// Diagnostics only. No image data or reference conversion table is embedded or written.
internal static class ColourAudit
{
    internal static void SelfTest(Action<bool, string> check)
    {
        // Independently generated by the pinned PCSX2 C++ function, via ssh-colour-check.py.
        // This hash covers RGB for every byte-valued Y/Cb/Cr, in that nesting order.
        const string expected = "65AF830BD857FE6F4355A32A12358FAB5E83393637F6656C71222D341C977C22";
        using var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        byte[] slice = new byte[256 * 256 * 3];
        for (int y = 0; y < 256; y++)
        {
            for (int cb = 0; cb < 256; cb++)
                for (int cr = 0; cr < 256; cr++)
                    Ssh.ConvertIpuRgb((byte)y, (byte)cb, (byte)cr, slice.AsSpan((cb * 256 + cr) * 3, 3));
            hash.AppendData(slice);
        }
        check(Convert.ToHexString(hash.GetHashAndReset()) == expected,
            "IPU CSC: all 16,777,216 synthetic inputs match the independent PCSX2 golden hash");
    }

    // The external table is generated by the pinned, unmodified PCSX2 reference function.
    // Its order is Y, then Cb, then Cr, with RGB bytes for each of the 256^3 inputs.
    internal static int CheckReference(string[] args)
    {
        if (args.Length is < 1 or > 2 || (args.Length == 2 && args[1] != "--perturb"))
        {
            Console.Error.WriteLine("usage: --check-colour <external-pcsx2-rgb-table> [--perturb]");
            return 1;
        }
        const int total = 256 * 256 * 256;
        using var input = File.OpenRead(args[0]);
        if (input.Length != total * 3) throw new InvalidDataException("Wrong colour table length.");
        byte[] expected = new byte[256 * 3];
        Span<byte> actual = stackalloc byte[3];
        int exact = 0, maxError = 0;
        for (int y = 0; y < 256; y++)
            for (int cb = 0; cb < 256; cb++)
            {
                input.ReadExactly(expected);
                for (int cr = 0; cr < 256; cr++)
                {
                    Ssh.ConvertIpuRgb((byte)y, (byte)cb, (byte)cr, actual);
                    if (args.Length == 2 && y == 0 && cb == 0 && cr == 0) actual[0] ^= 1;
                    bool same = actual.SequenceEqual(expected.AsSpan(cr * 3, 3));
                    if (same) exact++;
                    else if (maxError == 0)
                        Console.WriteLine($"First difference Y/Cb/Cr=({y},{cb},{cr}): " +
                            $"actual=({actual[0]},{actual[1]},{actual[2]}), " +
                            $"reference=({expected[cr * 3]},{expected[cr * 3 + 1]},{expected[cr * 3 + 2]}).");
                    for (int c = 0; c < 3; c++)
                        maxError = Math.Max(maxError, Math.Abs(actual[c] - expected[cr * 3 + c]));
                }
            }
        Console.WriteLine($"PCSX2 RGB exact: {exact} of {total} synthetic byte-input triples; maximum channel error {maxError}.");
        return exact == total ? 0 : 2;
    }

    internal static int Flat(string directory)
    {
        var pairs = Pairing.Find(directory);
        if (pairs.Count == 0) throw new InvalidDataException("No SSH files.");
        var rows = new List<FlatRow>();
        int flat = 0, flatExact = 0, flatRgbaExact = 0, paletted = 0, errors = 0;
        foreach (var pair in pairs)
        {
            if (pair.Error != null) continue;
            try
            {
                var reference = ReferenceImage.Read(pair.Tga!);
                if (!Metrics.IsFlat(reference.Pixels)) continue;
                flat++;
                byte[] data = File.ReadAllBytes(pair.Ssh);
                var image = new Ssh(data); // validate the real container and decode first
                if (image.Width != reference.Width || image.Height != reference.Height)
                    throw new InvalidDataException("Dimensions differ.");
                var metric = Metrics.Compare(image.Pixels, reference.Pixels);
                if (metric.Rgb == 0) flatExact++;
                if (metric.Rgb == 0 && metric.Alpha == 0) flatRgbaExact++;
                var entry = Ssh.ReadEntries(data)[0];
                if (entry.Type == 2) { paletted++; continue; }
                var gm = data.AsSpan(entry.Offset + 16, entry.Length - 16);
                int width = gm[2] * 16, height = gm[3] * 16, pixels = width * height;
                int length = (int)(BinaryPrimitives.ReadUInt32LittleEndian(gm[4..]) & 0xfffff);
                int alphaOffset = length - (image.HasAlpha ? pixels : 0);
                int end = -1;
                for (int i = alphaOffset - 4; i >= Math.Max(8, alphaOffset - 19); i--)
                    if (gm.Slice(i, 4).SequenceEqual(new byte[] { 0, 0, 1, 0x34 }) &&
                        ((i + 19) & ~15) == alphaOffset &&
                        gm.Slice(i + 4, alphaOffset - i - 4).IndexOfAnyExcept((byte)0) < 0)
                    { end = i; break; }
                if (end < 0) throw new InvalidDataException("No aligned GM terminator.");
                byte[] yuv = IpuDecoder.Decode(gm[8..end], width, height);
                bool constant = IsConstant(yuv.AsSpan(0, pixels)) &&
                    IsConstant(yuv.AsSpan(pixels, pixels / 4)) && IsConstant(yuv.AsSpan(pixels * 5 / 4));
                rows.Add(new FlatRow(Path.GetRelativePath(directory, pair.Ssh),
                    Pack(yuv[0], yuv[pixels], yuv[pixels * 5 / 4]),
                    Pack(reference.Pixels[0], reference.Pixels[1], reference.Pixels[2]), constant));
            }
            catch (Exception ex) { errors++; Console.WriteLine($"ERROR {pair.Ssh}: {ex.Message}"); }
        }
        Console.WriteLine($"Partners: {pairs.Count(p => p.Error == null)} of {pairs.Count} SSH files.");
        Console.WriteLine($"FLAT: RGB exact {flatExact} of {flat}; RGBA exact {flatRgbaExact} of {flat} flat references.");
        Console.WriteLine($"Compressed: {rows.Count} of {flat} flat references; paletted: {paletted} of {flat}.");
        Console.WriteLine($"Constant Y/Cb/Cr: {rows.Count(r => r.Constant)} of {rows.Count} decoded compressed flat references.");
        var groups = rows.Where(r => r.Constant).GroupBy(r => r.Yuv).ToArray();
        Console.WriteLine($"Conflicting RGB targets: {groups.Count(g => g.Select(r => r.Rgb).Distinct().Count() > 1)} " +
            $"of {groups.Length} distinct constant Y/Cb/Cr groups.");

        // Exhaust the input domain, never coefficients: can the fixed hardware mapping even
        // represent each reference colour? This is not a proposed alternative decoder.
        var targets = rows.Select(r => r.Rgb).ToHashSet();
        var reachable = new HashSet<int>();
        Span<byte> rgb = stackalloc byte[3];
        for (int y = 0; y < 256; y++)
            for (int cb = 0; cb < 256; cb++)
                for (int cr = 0; cr < 256; cr++)
                {
                    Ssh.ConvertIpuRgb((byte)y, (byte)cb, (byte)cr, rgb);
                    int packed = Pack(rgb[0], rgb[1], rgb[2]);
                    if (targets.Contains(packed)) reachable.Add(packed);
                }
        int unreachable = rows.Count(r => !reachable.Contains(r.Rgb));
        Console.WriteLine($"Unrepresentable by current CSC at ANY byte Y/Cb/Cr: {unreachable} of {rows.Count} " +
            $"compressed flat references; {targets.Count - reachable.Count} of {targets.Count} distinct target RGB colours.");
        foreach (var row in rows.Where(r => !reachable.Contains(r.Rgb)))
            Console.WriteLine($"UNREPRESENTABLE {row.File}");
        Console.WriteLine($"Audit errors: {errors} of {pairs.Count(p => p.Error == null)} paired files.");
        return errors == 0 ? 0 : 2;
    }

    static bool IsConstant(ReadOnlySpan<byte> values) => values[1..].IndexOfAnyExcept(values[0]) < 0;
    static int Pack(byte a, byte b, byte c) => a << 16 | b << 8 | c;
    sealed record FlatRow(string File, int Yuv, int Rgb, bool Constant);
}
