<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>tpwps2mp2gate</AssemblyName>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="NLayer" Version="1.16.0" /></ItemGroup>
</Project>
