<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>tpwps2check</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\core\TPW.PS2.Data\TPW.PS2.Data.csproj" />
    <ProjectReference Include="..\..\core\TPW.PS2.Launcher\TPW.PS2.Launcher.csproj" />
  </ItemGroup>
</Project>
